/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejerccio_de_donacion;

/**
 *
 * @author jcfoxer
 */
public class ejerccio_porcentajes extends javax.swing.JFrame {

    /**
     * Creates new form ejerccio_porcentajes
     */
    public ejerccio_porcentajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_don = new javax.swing.JTextField();
        txt_pe = new javax.swing.JTextField();
        txt_me = new javax.swing.JTextField();
        txt_gi = new javax.swing.JTextField();
        txt_tra = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txts = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("donacion general");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setText("pediatria  20% ( pediatria+ ginecologia)  ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("medicina  40% ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel4.setText("ginecologia  30% ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel5.setText("traumatologia     (lo que resta de la donacion ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 10));

        txt_don.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_donActionPerformed(evt);
            }
        });
        getContentPane().add(txt_don, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 80, -1));

        txt_pe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_peActionPerformed(evt);
            }
        });
        getContentPane().add(txt_pe, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 80, -1));
        getContentPane().add(txt_me, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 80, -1));
        getContentPane().add(txt_gi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 80, -1));
        getContentPane().add(txt_tra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 80, -1));

        txts.setColumns(20);
        txts.setRows(5);
        jScrollPane2.setViewportView(txts);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 370, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_donActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_donActionPerformed
        // TODO add your handling code here:
      //declaracion  de variables
 
        
        
        
        
    }//GEN-LAST:event_txt_donActionPerformed

    private void txt_peActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_peActionPerformed
        // TODO add your handling code here:
        
         double don,pe,me,gi,tra,porpe,porme,porgi,portra;      
      
        don=Double.parseDouble(txt_don.getText());
        pe=Double.parseDouble(txt_pe.getText());
        me=Double.parseDouble(txt_me.getText());
        gi=Double.parseDouble(txt_gi.getText());
        tra=Double.parseDouble(txt_tra.getText());
        
        //determina los procentajes 
        
        porpe=pe*0.20/don;
        porme=me*0.45/don;
        porgi=gi*0.30/don;
        portra=tra*0.05/don;
        
        
        //salida de resultados 
   txts.setText("donacion   :"+don +"\n");        
        
 txts.setText("procentaje pediatria  :"+porpe+"\n");    
 
 txts.setText("porcentaje de medicina:" +porme +"\n");        
txts.setText("porcentaje de ginecolgia:" +porgi +"\n");          
txts.setText("porcentaje de traumatologia:" +portra +"\n");          
        

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_txt_peActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejerccio_porcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejerccio_porcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejerccio_porcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejerccio_porcentajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejerccio_porcentajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_don;
    private javax.swing.JTextField txt_gi;
    private javax.swing.JTextField txt_me;
    private javax.swing.JTextField txt_pe;
    private javax.swing.JTextField txt_tra;
    private javax.swing.JTextArea txts;
    // End of variables declaration//GEN-END:variables
}
