
package venta_producto_unitarios_cantidad;
import java.awt.event.*;
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author jcfoxer
 */
public class ven_productos_unitarios_cantidad_05 extends javax.swing.JFrame {

    /**
     * Creates new form ven_productos_unitarios_cantidad_05
     */
    public ven_productos_unitarios_cantidad_05() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUnidades = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        btnProcesar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUnidadesActionPerformed(evt);
            }
        });
        getContentPane().add(txtUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 100, 30));

        btnBorrar.setText("BORRAR");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        btnProcesar.setText("CALCULAR");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 330, 140));

        jLabel1.setText("UNIDADES ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUnidadesActionPerformed

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
       
        {
   // Declaración de Variables
   int unidades;
   double icompra=0, idescuento=0, ipagar;
    
   // Entrada de Datos
   unidades = Integer.parseInt(txtUnidades.getText());
    
   // Cálcular el Importe de la Compra
   if (unidades >= 1 && unidades <=25)
    icompra = 27.7 * unidades;
   if (unidades >= 26 && unidades <= 50)
    icompra = 25.5 * unidades;
   if (unidades >= 51 && unidades <= 75)
    icompra = 23.5 * unidades;
   if (unidades >= 76)
    icompra = 21.5 * unidades;
    
   // Cálcular el Importe de Descuento
   if (unidades > 50)
    idescuento = 0.15 * icompra;
   if (unidades <= 50)
    idescuento = 0.05 * icompra; 
    
   // Cálcular el importe a pagar
   ipagar = icompra - idescuento;
    
   // Salida de Resultados
   txtArea.setText("Resultado" + "\n");
   txtArea.append("Importe de la Compra: " + icompra + "\n");
   txtArea.append("Importe de Descuento: " + idescuento + "\n");
   txtArea.append("Importe a Pagar: " + ipagar + "\n");
  }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        {
   txtUnidades.setText("");
   txtArea.setText("");
   txtUnidades.requestFocus();
    }//GEN-LAST:event_btnBorrarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ven_productos_unitarios_cantidad_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ven_productos_unitarios_cantidad_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ven_productos_unitarios_cantidad_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ven_productos_unitarios_cantidad_05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ven_productos_unitarios_cantidad_05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnProcesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtUnidades;
    // End of variables declaration//GEN-END:variables
}
