/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descuento_productoa_productob_productoc;

/**
 *
 * @author jcfoxer
 */
public class descuento_productoa_productob_productocc extends javax.swing.JFrame {

    /**
     * Creates new form descuento_productoa_productob_productocc
     */
    public descuento_productoa_productob_productocc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PRODUCTO A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 57, -1, -1));

        jLabel2.setText("PRODUCTO B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 94, -1, 23));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 53, -1, -1));

        jButton2.setText("BORRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 114, -1, -1));

        txta.setColumns(20);
        txta.setRows(5);
        jScrollPane1.setViewportView(txta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 175, 367, -1));

        jLabel3.setText("PRODUCTO C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 129, -1, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 70, -1));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 70, -1));
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         // Declaración de variables
   
         
    int  unidadesA, unidadesB,unidadesC;
   double icompraA, icompraB, idescuentoA, idescuentoB;
   Double icompratot, idescuentotot, ipagartot;
 
   // Entrada de datos
   unidadesA = Integer.parseInt(txt1.getText());
   unidadesB = Integer.parseInt(txt2.getText());
   unidadesC = Integer.parseInt(txt3.getText());
 
   // Determinar el importe bruto de ambos productos
   icompraA = unidadesA * 25.0;
   icompraB = unidadesB * 27.5;
 
   // Determinar el descuento del producto A
   if (unidadesA > 50)
    idescuentoA = 0.15 * icompraA;
   else
    idescuentoA = 0;
 
   // Determinar el descuento del producto B
   if (unidadesB > 35)
    idescuentoB = 0.10 * icompraB;
   else
    idescuentoB = 0;
 
   // Cálculo del importe bruto total
   icompratot = icompraA + icompraB;
 
   // Cálculo del importe de descuento total
   idescuentotot = idescuentoA + idescuentoB;
 
   // Cálculo del importe a pagar total
   ipagartot = icompratot - idescuentotot;
 
   // Salida de resultados
   txta.setText("-------------------" + "\n");
   txta.append("Importe de la compra total: " + icompratot + "\n");
   txta.append("Importe de descuento total: " + idescuentotot + "\n");
   txta.append("Importe a pagar total: " + ipagartot);
  }
  // Si hizo clic en Borrar
  {
   txtProductoA.setText("");
   txtProductoB.setText("");
   txtArea.setText("");
   txtProductoA.requestFocus();
  }
 
 }
}

        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
// Si hizo clic en Borrar
  if (e.getSource() == btnBorrar) {
   txtProductoA.setText("");
   txtProductoB.setText("");
   txtArea.setText("");
   txtProductoA.requestFocus();
  }
 
 }



    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(descuento_productoa_productob_productocc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(descuento_productoa_productob_productocc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(descuento_productoa_productob_productocc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(descuento_productoa_productob_productocc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new descuento_productoa_productob_productocc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextArea txta;
    // End of variables declaration//GEN-END:variables
}
