/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descuento_preoductoa_productob_prodcuto_c;

/**
 *
 * @author jcfoxer
 */
public class productoa_productob_productoc extends javax.swing.JFrame {

    /**
     * Creates new form productoa_productob_productoc
     */
    public productoa_productob_productoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("PRODUCTO  A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 35, -1, -1));

        jLabel2.setText("PRODUCTO B");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 96, -1, -1));

        jLabel3.setText("PRODUCTO C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 153, -1, -1));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 32, 140, -1));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 93, 140, -1));
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 150, 140, -1));

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 42, -1, -1));

        jButton2.setText("BORRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 116, -1, -1));

        txta.setColumns(20);
        txta.setRows(5);
        jScrollPane1.setViewportView(txta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 204, 341, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        int unidadesA,unidadesB,unidadesC;
        
      double   icompraa, icomprab,icomprac, idescuentoa, idescuentob,idescuentoc=0;
      Double icompratot, idescuentotot = null, ipagartot;
        
      unidadesA=Integer.parseInt(txt1.getText());
      unidadesB=Integer.parseInt(txt2.getText());
      unidadesC=Integer.parseInt(txt3.getText());  
        
       icompraa = unidadesA * 25.0;
     icomprab = unidadesB * 27.5;
     icomprac = unidadesC * 30.5;
        
        
         if (unidadesA > 50){
    idescuentoa = 0.15 * icompraa;}
   else
         {idescuentoa = 0;}
 
   // Determinar el descuento del producto B
   if (unidadesB > 35){
    idescuentob = 0.10 * icomprab;}
   else
   { idescuentob = 0;}
 
   // determinar el descuento del prodcuto c 
   
   if (unidadesC >20){
    idescuentoc = 0.08 * icomprac;}
   else{
    idescuentob = 0;}
   
    
//cuando la variable no puede ser inicilizada se pone al principio =0


    // Cálculo del importe bruto total
   icompratot = icompraa + icomprab+icomprac;
 
   // Cálculo del importe de descuento total
   idescuentotot = idescuentoa + idescuentob+idescuentoc;
   
   
   // Cálculo del importe a pagar total
   ipagartot = icompratot-idescuentotot;   
   
   
   
   
   
   // Salida de resultados
   txta.setText("-------------------" + "\n");
   txta.append("Importe de la compra total: " + icompratot + "\n");
   txta.append("Importe de descuento total: " +idescuentotot+"\n");
   txta.append("Importe a pagar total: " + ipagartot);
  
   
   
   
   
   
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     txt1.setText("");
   txt2.setText("");
  txt3.setText("");
   txta.setText("");
  
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productoa_productob_productoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productoa_productob_productoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productoa_productob_productoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productoa_productob_productoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productoa_productob_productoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextArea txta;
    // End of variables declaration//GEN-END:variables
}
