/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//debora raquel y sefora aportan cantidades de dinero para formar un capital
//diseñe un porgrama que determine el capital formado y el porcentaje de dicho capital que aportan cada uno 
/**
 *
 * @author jcfoxer
 */
public class reparto_dinero extends javax.swing.JFrame {

    /**
     * Creates new form reparto_dinero
     */
    public reparto_dinero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdinerodebora = new javax.swing.JTextField();
        txtdineroraquel = new javax.swing.JTextField();
        txtdinerosefora = new javax.swing.JTextField();
        btn_procesar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txts = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("dinero de debora");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setText("dinero de raquel");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setText("dinero de sefora");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtdinerodebora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdinerodeboraActionPerformed(evt);
            }
        });
        getContentPane().add(txtdinerodebora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 70, -1));
        getContentPane().add(txtdineroraquel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 70, -1));

        txtdinerosefora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdineroseforaActionPerformed(evt);
            }
        });
        getContentPane().add(txtdinerosefora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 70, -1));

        btn_procesar.setText("procesar");
        btn_procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_procesarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_procesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        txts.setColumns(20);
        txts.setRows(5);
        jScrollPane1.setViewportView(txts);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 340, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdineroseforaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdineroseforaActionPerformed
     
        //decklaracion de varibles siempre en event action event 
        double dinedeb,dineraq,dinesef,capital,porcdeb,porcraq,porsef;
        //entrada de datos 
        dinedeb=Double.parseDouble(txtdinerodebora.getText());
        dineraq=Double.parseDouble(txtdineroraquel.getText());
        dinesef=Double.parseDouble(txtdinerosefora.getText());
        
        // determina la  cantidad formado 
        
        capital=dinedeb+dineraq+dinesef;
        
        //determina los procentajes 
        
        porcdeb=dinedeb*100/capital;
         porcraq=dineraq*100/capital;
          porsef=dinesef*100/capital;
          
    //salida de resultados 
 txts.setText("capital           :"+capital+"\n");    
txts.append("porcentaje de debora:" +porcdeb +"\n");        
txts.append("porcentaje de raquel:" +porcraq +"\n");          
txts.append("porcentaje de sefora:" +porsef +"\n");          
        
    }//GEN-LAST:event_txtdineroseforaActionPerformed
//el porgrama se ejecuta pero solo con enter  no con el boton 
    
    
    
    private void btn_procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_procesarActionPerformed
    }//GEN-LAST:event_btn_procesarActionPerformed

    private void txtdinerodeboraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdinerodeboraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdinerodeboraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reparto_dinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reparto_dinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reparto_dinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reparto_dinero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new reparto_dinero().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_procesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtdinerodebora;
    private javax.swing.JTextField txtdineroraquel;
    private javax.swing.JTextField txtdinerosefora;
    private javax.swing.JTextArea txts;
    // End of variables declaration//GEN-END:variables
}
